export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const OUTLET = "OUTLET";

export const NEW_COLLECTION = "NEW_COLLECTION";

export const SEARCH = "SEARCH";